# Generated by Django 2.1.7 on 2019-02-17 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190218_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 21, 44, 15, 547247, tzinfo=utc)),
        ),
    ]
